# H2 Database 
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:product
    driver-class-name: org.h2.Driver
    username: jsencler
    password: 123456
  jpa:
    defer-datasource-initialization: true
    show-sql: true