DROP TABLE product IF EXISTS;

CREATE TABLE product(
	PRODUCTS_NO INTEGER NOT NULL AUTO_INCREMENT,
	PRODUCT_NAME VARCHAR(50) NOT NULL,
	QUANTITY INTEGER NOT NULL DEFAULT 0,
    	PRICE DECIMAL (12,2) DEFAULT 0.00,
	PRIMARY KEY  (PRODUCTS_NO)
);

